/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:ae37cb55-2fc5-47e5-8fcf-b1df1c38390d',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_zsRt0pkwe',
  aws_user_pools_web_client_id: '70t4eu3s0ctbj953jadc1skji9',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://vqphm3uiv5g4pl6erfkrt4pxqi.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-tfj7fguqf5cplf4hwgqvghfuj4',
  aws_user_files_s3_bucket: 'selene-amplify14031-staging',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
